### ISSUE TITLE
New Member Signup Question

### ISSUE THREAD

**Issue by alanruth** [jekuno/milia#19]
Thanks for your work on this! I am using it for a couple of projects now. 

When I add a new member for a tenant, a password is being generated and used for the user creation for devise. The email goes out with a confirmation link. When they click on the link, it automatically logs them in and puts them on the welcome screen.

I also see this in the code and of particular interest is the change_or_confirm_user and  line 38: if ( @confirmable.skip_confirm_change_password || @confirmable.valid? )

In the situation I described, I would have thought this would have returned false and thus would hit the else statement on line 40. However it appears to be resulting in true and executing the do_confirm (which logs them in automatically). Yet my new member never gets to set up their own password via a show view that I build and your update method.

I may not be following the code correct but any guidance would be appreciated.

**Comment by philsmy** [comment]
Hi,
I know this issue is closed, but, I don't understand how it is supposed to behave and in the sample app I am seeing the behaviour described above:
* create clean sample app
* sign up for organisation
* invite member
* go to member confirmation link and it asks me to sign in, but, I have no idea what the password is

How to get members to go to the password page? Or even to get them logged in automatically?

**Comment by dsaronin** [comment]
It's been a while since I've looked at this. But yes, the ORGANIZER is the
first one to sign up for his organization, at that time the ORGANIZER
creates a password once he has activated his link. To get other members
into the same organization, he then clicks a link to invite new MEMBER,
entering the new MEMBER's email into the form. The system then sends an
activation email to the member, who then needs to click the activation
link. That should take the MEMBER to a page requesting MEMBER to create a
password. once that is submitted, then thereafter MEMBER can enter system
via the sign-in page/link.

The confirmation link should NOT be directing to the sign in page.

**Comment by philsmy** [comment]
Ok...that's definitely NOT what's happening (and the organizer creates his own password on the signup form).
I followed the doc/sample.sh to create the sample app, and I double checked and everything seems right.
How to debug why this is sending me to a login page?

**Comment by dsaronin** [comment]
owner doesn't create it on the signup form; password creation occurs after
activation.

**Comment by MatthewMarkgraaff** [comment]
Hey guys.

I am currently experiencing the same issue. When inviting a new member, an activation link is created (as expected). If I follow the link to activate that particular users account, I am presented with the login form. The user is successfully confirmed but has no opportunity to create their own password etc. 

I thought this was intentionally left out of Milia's out of the box offering and I would need to extend on it myself but it seems like it may be a bug? 

On a side note, I am really enjoying working with Milia so far, thank you!

**Comment by philsmy** [comment]
To be honest, I solved this by using cortexinsight's fork. It fixed the problem (even for the sample app). Now everything works as expected. By switching to that fork I also discovered that my confirmations were never right... they never auto-logged in the tenant own, but presented a login screen. (same thing happens in the clean sample app)

**Comment by vinny1575** [comment]
Having this same issue. I Was going to override the devise confirmation controller, but realized that milia is already doing that. Any ideas?
