### ISSUE TITLE
Upgrade path from 1.2.x to 1.3.x

### ISSUE THREAD

**Issue by waruboy** [jekuno/milia#70]
Hello,

I'm planning to build a new multitenanted application using Rails 4.2 (since there are some gems that I want to use that is not Rails 5 ready) and Milia. Looks like I will have to use Milia version 1.2.x.

My question is, when the time comes that I upgrade to Rails 5, can I simply upgrade the Milia gem to 1.3.x ? Is there any specific steps that I have to follow?

I suggest to put this information in the readme.

Thanks before!

**Comment by jekuno** [comment]
Upgrading is pretty straight forward. Migrate your app to Rails 5 and devise ~> 4.2 and you should be able to switch to milia 1.3 or newer.
I updated https://github.com/jekuno/milia/blob/master/CHANGELOG.md#v13x accordingly.
Feel free to contact me if you find any additional steps which need to be done.
(btw I would recommend to start with Rails 5 instead of 4.2 if you start a new app from scratch - but you seem to have your reasons)

**Comment by waruboy** [comment]
got it! Thanks for responding! @jekuno
