### ISSUE TITLE
Complare to ErwinM/acts_as_tenant

### ISSUE THREAD

**Issue by razum2um** [jekuno/milia#71]
https://github.com/ErwinM/acts_as_tenant gem uses same approach to row based tenancy and nearly same api & default_scopes & also appeared in 2011 (as this one, wow)

Could you shortly overview what makes the difference?

**Comment by jekuno** [comment]
I hadn't been on board when `milia` was planted but the use of wordings like `tenant`, `current_tenant` and `set_current_tenant` seems to be an obvious decision when developing a multi tenanting gem. ;) 

Decision for row based instead of schema based architecture was made for good reasons, see http://myrailscraft.blogspot.de/2013/05/multi-tenanting-ruby-on-rails_4470.html and https://github.com/jekuno/milia/blob/master/README_DETAILS.md#row-based-vs-schema-based-tenanting for details. Using default scopes is the most natural way to fulfill the multi tenanting requriements.

I don't know the other gem too well but a big difference is that milia supports devise out of the box (see https://github.com/jekuno/milia#milia-highlights). Also milia is very strict in enforcing tenanting and preventing illegal access but also allows you to designate universal models which will not get tenanted at the same time.

Feel free to compare the two gems in more detail yourself. Both gems seem to have a mature state so you won't make a mistake choosing either of them!
